upstream active_service { server team8-web:8001; }
server {
    listen 80;
    location / {
        proxy_pass http://active_service;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_connect_timeout 5s;
        proxy_read_timeout 30s;
    }
    location /nginx-health {
        return 200 '{"status":"ok"}';
        add_header Content-Type application/json;
    }
}